# .graphclientrc.yml
sources:
  - name: treeController
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/44385/scaling-tree/v0.0.22
    transforms: # The following section will make sure to automatically fetch the block information, and then use it for tracking in future queries.
      - blockTracking:
          validateSchema: true # Validates that the schema source actually contains _meta and input block filters.

documents:
  - queries/*.graphql
