/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITreeAuditorRegistry } from "./ITreeAuditorRegistry";
export type { ITreeController } from "./ITreeController";
export type { ITreeNFT } from "./ITreeNFT";
