/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ITreeAuditorRegistryInterface extends utils.Interface {
  functions: {
    "addAuditor(address)": FunctionFragment;
    "isAuditor(address)": FunctionFragment;
    "removeAuditor(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addAuditor" | "isAuditor" | "removeAuditor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAuditor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuditor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuditor",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "addAuditor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAuditor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAuditor",
    data: BytesLike
  ): Result;

  events: {
    "AuditorAdded(address)": EventFragment;
    "AuditorRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuditorAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuditorRemoved"): EventFragment;
}

export interface AuditorAddedEventObject {
  auditor_: string;
}
export type AuditorAddedEvent = TypedEvent<[string], AuditorAddedEventObject>;

export type AuditorAddedEventFilter = TypedEventFilter<AuditorAddedEvent>;

export interface AuditorRemovedEventObject {
  auditor_: string;
}
export type AuditorRemovedEvent = TypedEvent<
  [string],
  AuditorRemovedEventObject
>;

export type AuditorRemovedEventFilter = TypedEventFilter<AuditorRemovedEvent>;

export interface ITreeAuditorRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITreeAuditorRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAuditor(
      auditor_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addAuditor(
    auditor_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isAuditor(
    auditor: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeAuditor(
    auditor: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addAuditor(
      auditor_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AuditorAdded(address)"(
      auditor_?: PromiseOrValue<string> | null
    ): AuditorAddedEventFilter;
    AuditorAdded(
      auditor_?: PromiseOrValue<string> | null
    ): AuditorAddedEventFilter;

    "AuditorRemoved(address)"(
      auditor_?: PromiseOrValue<string> | null
    ): AuditorRemovedEventFilter;
    AuditorRemoved(
      auditor_?: PromiseOrValue<string> | null
    ): AuditorRemovedEventFilter;
  };

  estimateGas: {
    addAuditor(
      auditor_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAuditor(
      auditor_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAuditor(
      auditor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
